#---
#collections:
  #- src: https://github.com/ansible-collections/cisco.iosxr
    #type: git
   # version: 3.2.0
  #  name: cisco.iosxr
 #   
#  - src: https://github.com/ansible/pylibssh
  #  #type: git
 #   version: 0.4.0
#    name: pylibssh


---

- src: https://github.com/plone/ansible.plone_server.git
  version: 1.3.8
  name: plone.plone_server

- src: https://github.com/jnv/ansible-role-unattended-upgrades.git
  version: v1.5.0
  name: jnv.unattended-upgrades
