---
#collections:
  - src: https://github.com/ansible-collections/cisco.iosxr
    #type: git
    version: 3.2.0
    name: cisco.iosxr
    
  - src: https://github.com/ansible/pylibssh
    #type: git
    version: 0.4.0
    name: pylibssh
