---
- name: testDir sample
  hosts: all
  connection: local
  tasks:
    - name: playbook dir
      debug:
        msg: "{{playbook_dir}}"
    - name: testing Debug
      debug:
        msg: "testing Debug"
  
    - name: config netsim
      tasks:
    - name: Configure a device
      cisco.iosxr.iosxr_interfaces:
       config:
       - name: GigabitEthernet0/0/0/2
         description: Configured by Ansible
         enabled: true
       - name: GigabitEthernet0/0/0/3
         description: Configured by Ansible Network
         enabled: false
         duplex: full
       state: merged
