---
- name: testDir sample
  hosts: netSims
  gather_facts: no
  #ansible_network_cli_ssh_type: libssh
  become: yes
  connection: local
  tasks:
    - name: playbook dir print
      debug:
        msg: "{{playbook_dir}}"

      #second task
- name: Configure netsim
  hosts: netSims
  gather_facts: no
  become: yes
  tasks:
      - name: Configure a device
        cisco.iosxr.iosxr_interfaces:
         config:
         - name: GigabitEthernet0/0/0/2
           description: Configured by Ansible
           enabled: true
         - name: GigabitEthernet0/0/0/3
           description: Configured by Ansible Network
           enabled: false
           duplex: full
         state: merged
