---
- name: testDir sample
  hosts: 127.0.0.1
  gather_facts: no
  connection: local
  ansible_network_cli_ssh_type: libssh
  tasks:
    - name: playbook dir print
      debug:
        msg: "{{playbook_dir}}"
    - name: Find out playbook's path
      shell: pwd
      register: playbook_path_output
    - debug: var=playbook_path_output.stdout
    
    - name: run show version command
      ansible.netcommon.cli_command:
       command: show version

    - name: run show interface command
      ansible.netcommon.cli_command:
       command: show interfaces
      #second task
- name: Configure netsim
  hosts: 127.0.0.1
  gather_facts: no
  become: no
  tasks:
      - name: Configure a device
        cisco.iosxr.iosxr_interfaces:
         config:
         - name: GigabitEthernet0/0/0/2
           description: Configured by Ansible
           enabled: true
         - name: GigabitEthernet0/0/0/3
           description: Configured by Ansible Network
           enabled: false
           duplex: full
         state: merged
