- hosts: 127.0.0.1
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    #ansible_user: "changeme"
    #ansible_password: "changeme"
    ansible_network_cli_ssh_type: libssh
  tasks:
  - name: run show version command
    ansible.netcommon.cli_command:
      command: show version

  - name: run show version command
    ansible.netcommon.cli_command:
      command: show interfaces
